### ISSUE TITLE
Why does ratel not have tolerations or nodeSelector ? alpha and zero have it 

### ISSUE THREAD

**Issue by orange-oranje** [dgraph-io/charts#15]
Is the reason why it is skipped for ratel

**Comment by darkn3rd** [comment]
Ratel is an independent component that is self-contained.  This should actually be deployed in its own namespace, so that security measures, such as network policies or [SMI](https://github.com/servicemeshinterface/smi-spec) CRDs to wall off Ratel from rest of the cluster.
