### ISSUE TITLE
Feature request: Support for TLS

### ISSUE THREAD

**Issue by dpkirchner** [dgraph-io/charts#16]
It'd be useful to have a way to enable TLS in the chart. Ideally, the chart would allow you to enable TLS and configure the `tls_client_auth` flag (defaulting to `REQUIREANDVERIFY`), and allow you to provide your own TLS CA and node certificates. It would need a way to provide a client certificate for health checking, to conditionally replace the `livenessProbe` (so it'd use curl).

**Comment by darkn3rd** [comment]
Dgraph TLS feature can be supported through adding a configuration file, see https://github.com/dgraph-io/charts/tree/master/charts/dgraph/example_values.  I have tested this with public trusted CA certs and self-sign ones generated by `dgraph cert`.

Optimaly, I would recommend using cert-manager for north-south traffic, such as an ingress, or use an east-west (eBPF CNI or service mesh).
