### ISSUE TITLE
Helm chart defaults to cluster.local.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/charts#18]
It should not always default to the *cluster.local dns name.

**Comment by darkn3rd** [comment]
Would these be configured to something besides the hostname internal to Kubernetes?  
Thus the command to run the container is using get from `hostname -f`.  This is setup inside the `/etc/hosts`:

```
192.168.6.92	dgraph-1589489873-dgraph-alpha-0.dgraph-1589489873-dgraph-alpha-headless.default.svc.cluster.local	dgraph-1589489873-dgraph-alpha-0
```

Is the name generated outside of Kubernetes, something we'd could or want to change?

**Comment by danielmai** [comment]
Are you suggesting we use `dgraph-1589489873-dgraph-alpha-0` instead of the FQDN of the service `dgraph-1589489873-dgraph-alpha-0.dgraph-1589489873-dgraph-alpha-headless.default.svc.cluster.local`?
