### ISSUE TITLE
why is persistence a MUST?

### ISSUE THREAD

**Issue by encryptblockr** [dgraph-io/charts#23]
seems it is not possible to deploy this helm charts without having persistence enabled
what about deploying this on baremetal and want to use local storage?
how can one disable persistence? why is persistence enforced?

```
Release "dgraph" does not exist. Installing it now.
Error: YAML parse error on dgraph/templates/alpha-statefulset.yaml: error converting YAML to JSON: yaml: line 66: did not find expected key
```

**Comment by MrSimonEmms** [comment]
I think it's because of [this line](https://github.com/dgraph-io/charts/blob/master/charts/dgraph/templates/alpha-statefulset.yaml#L169). Looks like it's missing the key if persistence is disabled
