### ISSUE TITLE
will there be a new version for v22.0.2?

### ISSUE THREAD

**Issue by hankhsutc** [dgraph-io/charts#82]
dgraph v22.0.2 is GA. will there be a new version for it?
if not, which chart version should I use? 0.0.19(tag: v21.12.0) or 0.0.18(tag: v21.03.1)

**Comment by mprimeaux** [comment]
Currently, I only see `0.0.19` in the Helm index even though [0.0.20 seems to be the latest](https://github.com/dgraph-io/charts/blob/31cef32774e847fcae253b92ff751c5e86bde972/charts/dgraph/Chart.yaml#L3).

```shell
helm search repo graph
NAME                	CHART VERSION	APP VERSION	DESCRIPTION
dgraph/dgraph       	0.0.19       	v21.12.0   	Dgraph is a horizontally scalable and distribut...
dgraph/dgraph-lambda	0.0.2        	v1.2.4     	Serverless platform for running JavaScript on S...
```

**Comment by mprimeaux** [comment]
When will version `0.0.20` be in the Helm index?

**Comment by mprimeaux** [comment]
I was able to specify the more recent container images from [DockerHub](https://hub.docker.com/r/dgraph/dgraph/tags) in the `image` stanza:

```yaml
image:
  repository: dgraph/dgraph
  tag: latest
  pullPolicy: IfNotPresent
```

Hopefully, any changes to the related Helm chart are updated soon.

**Comment by mprimeaux** [comment]
Any updates on the v22 version of dgraph?
